# Generated by Django 6.0.5 on 2026-05-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Next-Gen Property Management', max_length=200)),
                ('hero_subtitle', models.TextField(default='CyberProp combines cutting-edge technology with expert property management to deliver seamless experiences for tenants, owners, and investors.')),
                ('stat_properties', models.CharField(default='150+', max_length=20)),
                ('stat_properties_label', models.CharField(default='Properties Managed', max_length=60)),
                ('stat_tenants', models.CharField(default='500+', max_length=20)),
                ('stat_tenants_label', models.CharField(default='Happy Tenants', max_length=60)),
                ('stat_occupancy', models.CharField(default='98%', max_length=20)),
                ('stat_occupancy_label', models.CharField(default='Occupancy Rate', max_length=60)),
                ('stat_portfolio', models.CharField(default='R50M+', max_length=20)),
                ('stat_portfolio_label', models.CharField(default='Portfolio Value', max_length=60)),
                ('about_tagline', models.CharField(default='Smart property management for the modern era', max_length=200)),
                ('about_mission_title', models.CharField(default='Our Mission', max_length=200)),
                ('about_mission_text', models.TextField(default='CyberProp was founded with a simple vision: to revolutionise property management in South Africa through technology. We believe that managing properties should be transparent, efficient, and accessible to everyone — from individual landlords to large-scale investors.')),
                ('about_mission_text_2', models.TextField(blank=True, default='Our platform combines decades of property management expertise with cutting-edge software to deliver an experience that benefits tenants, property owners, and investors alike.')),
                ('about_established', models.CharField(default='Est. 2024', max_length=20)),
                ('about_location', models.CharField(default='Cape Town, South Africa', max_length=100)),
                ('contact_email', models.EmailField(default='info@cyberprop.co.za', max_length=254)),
                ('contact_phone', models.CharField(default='+27 21 000 0000', max_length=30)),
                ('contact_address', models.TextField(default='CyberProp Property Management\nCape Town, Western Cape\nSouth Africa')),
                ('contact_hours_weekday', models.CharField(default='Monday – Friday: 08:00 – 17:00', max_length=60)),
                ('contact_hours_saturday', models.CharField(default='Saturday: 09:00 – 13:00', max_length=60)),
                ('cta_title', models.CharField(default='Ready to Get Started?', max_length=200)),
                ('cta_subtitle', models.TextField(default="Whether you're looking for a rental, want your property managed, or interested in investing — CyberProp has you covered.")),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
